app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

editor_upload:
    pattern: /editor_upload
    defaults: { _controller: AppBundle:Image:editorUpload }

