admin_homepage:
    path: /
    defaults: { _controller: AdminBundle:Default:index }

admin_order:
    path: /order
    defaults: { _controller: AdminBundle:Order:index }

admin_product:
    path: /product
    defaults: { _controller: AdminBundle:Product:index }

admin_product_add:
    path: /product/add
    defaults: { _controller: AdminBundle:Product:add }

admin_product_edit:
    path: /product/{id}/edit
    defaults: { _controller: AdminBundle:Product:edit }

admin_product_sku_add:
    path: /product/{productId}/sku/add
    defaults: { _controller: AdminBundle:ProductSku:add }
    requirements:
        productId: \d+

admin_product_category:
    path: /product/category
    defaults: { _controller: AdminBundle:ProductCategory:index }
    
admin_category_add:
    path: /product/category/add
    defaults: { _controller: AdminBundle:ProductCategory:add }

admin_category_edit:
    path: /product/category/{id}/edit
    defaults: { _controller: AdminBundle:ProductCategory:edit }

admin_category_delete:
    path: /product/category/{id}/{type}
    defaults: { _controller: AdminBundle:ProductCategory:switch }
    requirements:
        id: \d+
        type: enable|disable
    methods: [POST, PUT]

admin_category_load:
    path: /product/category/load
    defaults: { _controller: AdminBundle:ProductCategory:load }

admin_category_load_select:
    path: /product/category/select/{id}/load
    defaults: { _controller: AdminBundle:ProductCategory:selectLoad }
    
admin_user:
    path: /user
    defaults: { _controller: AdminBundle:User:index }

admin_system:
    path: /system
    defaults: { _controller: AdminBundle:System:index }
