admin_homepage:
    path: /
    defaults: { _controller: AdminBundle:Default:index }

admin_order:
    path: /order
    defaults: { _controller: AdminBundle:Order:index }

admin_product:
    path: /product
    defaults: { _controller: AdminBundle:Product:index }

admin_product_category:
    path: /product/category
    defaults: { _controller: AdminBundle:ProductCategory:index }
    
admin_category_add:
    path: /product/category/add
    defaults: { _controller: AdminBundle:ProductCategory:add }

admin_category_load:
    path: /product/category/load
    defaults: { _controller: AdminBundle:ProductCategory:load }
    
admin_user:
    path: /user
    defaults: { _controller: AdminBundle:User:index }

admin_system:
    path: /system
    defaults: { _controller: AdminBundle:System:index }
