admin_homepage:
    path: /
    defaults: { _controller: AdminBundle:Default:index }

admin_order:
    path: /order
    defaults: { _controller: AdminBundle:Order:index }

admin_product:
    path: /product
    defaults: { _controller: AdminBundle:Product:index }

admin_product_add:
    path: /product/add
    defaults: { _controller: AdminBundle:Product:add }

admin_product_edit:
    path: /product/{id}/edit
    defaults: { _controller: AdminBundle:Product:edit }
    requirements:
        id: \d+

admin_product_delete:
    path: /product/delete
    defaults: { _controller: AdminBundle:Product:delete }
    methods: [POST]

admin_product_detail:
    path: /product/{id}/detail
    defaults: { _controller: AdminBundle:ProductSku:detail }
    requirements:
        id: \d+

admin_product_sku_add:
    path: /product/{productId}/sku/add
    defaults: { _controller: AdminBundle:ProductSku:add }
    requirements:
        productId: \d+

admin_product_category:
    path: /product/category
    defaults: { _controller: AdminBundle:ProductCategory:index }
    
admin_category_add:
    path: /product/category/add
    defaults: { _controller: AdminBundle:ProductCategory:add }

admin_category_edit:
    path: /product/category/{id}/edit
    defaults: { _controller: AdminBundle:ProductCategory:edit }
    requirements:
        id: \d+

admin_category_delete:
    path: /product/category/{id}/{type}
    defaults: { _controller: AdminBundle:ProductCategory:switch }
    requirements:
        id: \d+
        type: enable|disable
    methods: [POST, PUT]

admin_category_load:
    path: /product/category/load
    defaults: { _controller: AdminBundle:ProductCategory:load }

admin_category_load_select:
    path: /product/category/select/load
    defaults: { _controller: AdminBundle:ProductCategory:selectLoad }

admin_brand:
    path: /brand
    defaults: { _controller: AdminBundle:Brand:index }

admin_brand_name_check:
    path: /brand/name/check
    defaults: { _controller: AdminBundle:Brand:nameCheck }

admin_brand_edit_name_check:
    path: /brand/edit/{id}/name/check
    defaults: { _controller: AdminBundle:Brand:editNameCheck }

admin_brand_add:
    path: /brand/add
    defaults: { _controller: AdminBundle:Brand:add }

admin_brand_logo_upload:
    path: /brand/logo/upload
    defaults: { _controller: AdminBundle:Brand:logoUpload }

admin_brand_detail:
    path: /brand/{id}/detail
    defaults: { _controller: AdminBundle:Brand:detail }
    requirements:
        id: \d+

admin_brand_edit:
    path: /brand/{id}/edit
    defaults: { _controller: AdminBundle:Brand:edit }
    requirements:
        id: \d+

admin_brand_switch:
    path: /brand/{id}/{type}/switch
    defaults: { _controller: AdminBundle:Brand:switch }
    requirements:
        id: \d+
        type: enable|disable
    methods: [POST, PUT]

admin_brand_delete:
    path: /brand/delete
    defaults: { _controller: AdminBundle:Brand:delete }
    methods: [POST, PUT]
    
admin_user:
    path: /user
    defaults: { _controller: AdminBundle:User:index }

admin_system:
    path: /system
    defaults: { _controller: AdminBundle:System:index }
